<?php
$pageTitle = 'Mines Game';
require_once __DIR__ . '/../includes/header.php';
?>

<div class="container">
    <h1 class="section-title">💣 Mines Game</h1>
    
    <div class="game-container" style="max-width: 800px; margin: 0 auto;">
        <div style="text-align: center; margin-bottom: 2rem;">
            <p style="font-size: 1.1rem; color: #ccc;">Reveal safe tiles to increase your multiplier. But watch out for mines!</p>
        </div>
        
        <div style="background: linear-gradient(135deg, var(--bg-card), var(--secondary-light)); padding: 2rem; border-radius: 20px; border: 3px solid var(--primary); box-shadow: 0 0 30px var(--shadow-gold);">
            
            <!-- Game Stats -->
            <div style="display: flex; justify-content: space-around; margin-bottom: 2rem; flex-wrap: wrap; gap: 1rem;">
                <div style="text-align: center;">
                    <div style="color: #ccc;">Bet Amount</div>
                    <div id="current-bet" style="color: var(--primary); font-size: 1.5rem; font-weight: bold;">0</div>
                </div>
                <div style="text-align: center;">
                    <div style="color: #ccc;">Tiles Revealed</div>
                    <div id="tiles-revealed" style="color: var(--success); font-size: 1.5rem; font-weight: bold;">0</div>
                </div>
                <div style="text-align: center;">
                    <div style="color: #ccc;">Current Multiplier</div>
                    <div id="current-multiplier" style="color: var(--warning); font-size: 1.5rem; font-weight: bold;">1.00x</div>
                </div>
                <div style="text-align: center;">
                    <div style="color: #ccc;">Potential Win</div>
                    <div id="potential-win" style="color: var(--primary); font-size: 1.5rem; font-weight: bold;">0</div>
                </div>
            </div>
            
            <!-- Mines Grid -->
            <div id="mines-grid" style="display: grid; grid-template-columns: repeat(5, 1fr); gap: 10px; margin-bottom: 2rem; max-width: 500px; margin-left: auto; margin-right: auto;">
                <!-- Grid will be generated by JavaScript -->
            </div>
            
            <div id="game-message" style="text-align: center; min-height: 50px; font-size: 1.3rem; font-weight: bold; margin-bottom: 1rem;"></div>
            
            <!-- Game Controls -->
            <div id="start-controls" class="game-controls">
                <div style="display: flex; align-items: center; gap: 1rem; flex-wrap: wrap;">
                    <label style="color: var(--primary); font-weight: bold;">Bet Amount:</label>
                    <select id="bet-amount" class="bet-input">
                        <option value="10">10 Coins</option>
                        <option value="50" selected>50 Coins</option>
                        <option value="100">100 Coins</option>
                        <option value="250">250 Coins</option>
                        <option value="500">500 Coins</option>
                    </select>
                    
                    <label style="color: var(--primary); font-weight: bold;">Mines:</label>
                    <select id="mine-count" class="bet-input">
                        <option value="3">3 Mines (Easy)</option>
                        <option value="5" selected>5 Mines (Medium)</option>
                        <option value="8">8 Mines (Hard)</option>
                        <option value="10">10 Mines (Expert)</option>
                    </select>
                </div>
                <button onclick="startGame()" class="btn btn-primary" style="font-size: 1.1rem;">Start Game</button>
            </div>
            
            <div id="cashout-controls" class="game-controls" style="display: none;">
                <button onclick="cashOut()" class="btn btn-primary" style="font-size: 1.1rem; background: var(--success);">Cash Out</button>
                <button onclick="resetGame()" class="btn btn-secondary" style="font-size: 1.1rem;">New Game</button>
            </div>
        </div>
        
        <!-- How to Play -->
        <div style="margin-top: 3rem; background: var(--bg-card); padding: 2rem; border-radius: 15px; border: 1px solid var(--primary);">
            <h3 style="color: var(--primary); margin-bottom: 1rem;">📖 How to Play</h3>
            <ol style="color: #ccc; line-height: 2;">
                <li>Choose your bet amount and number of mines</li>
                <li>Click "Start Game" to begin</li>
                <li>Click on tiles to reveal them - avoid the mines!</li>
                <li>Each safe tile increases your multiplier</li>
                <li>Cash out anytime to collect your winnings</li>
                <li>Hit a mine and you lose your bet!</li>
            </ol>
            <p style="color: var(--warning); margin-top: 1rem;">💡 Tip: More mines = higher multipliers but greater risk!</p>
        </div>
    </div>
</div>

<script src="/js/wallet.js"></script>
<script src="/js/game-history.js"></script>
<script src="/js/mines.js"></script>

<?php require_once __DIR__ . '/../includes/footer.php'; ?>
